//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoWebApi
{


    public partial class Reservation
    {
         public int ReservationId { get; set; }
       
        public int AccountId { get; set; }

        public string FirstName { get; set; }

       
        public int CarId { get; set; }

        public string CarName { get; set; }

      
        public System.DateTime RentalDate { get; set; }

        public System.DateTime ReturnDate { get; set; }

       
    }
}
